
name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.18.3
      
      - name: Link Node
        run: "ln -s /opt/hostedtoolcache/node/12.18.3/x64/bin/nodejs /opt/hostedtoolcache/node/12.18.3/x64/bin/node


      - name: Install docsy prerequisites
        run: npm install

      - name: Hugo Deploy GitHub Pages
        uses: benmatselby/hugo-deploy-gh-pages@master
        env:
          HUGO_VERSION: 0.74.3
          HUGO_EXTENDED: true
          TARGET_REPO: ngfreiter/fsh-school-test.github.io
          TOKEN: ${{ secrets.TOKEN }}
          CNAME: fshschool.org
          HUGO_ARGS: -v