
name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.18.3

      - name: Install docsy prerequisites
        run: npm install

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.74.3'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: ngfreiter/test-fshschool-site.github.io
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./public